name: shop_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  mysql1: ^0.20.0
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  pdf: ^3.7.1
  printing: ^5.10.5
  path_provider: ^2.0.15
  universal_platform: ^1.0.0+1
  universal_html: ^2.2.4
  open_filex: ^4.6.0
  responsive_framework: ^0.1.7
  flutter_spinbox: ^0.13.1
  animations: ^2.0.7
  google_fonts: ^6.1.0
  flutter_pdfview: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/cinnamorrollnurse.png
    - assets/images/cinamon.png
    - assets/fonts/Roboto-Regular.ttf