name: shop_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1Join 30 Million
  developers who use
  Postman
  Simplify your API design, development and testing
  workflows with Postman.
  Save and organize your work in collections and workspaces
  Share your work with clients and collaborate with teammates
  Integrate with tools like VS Code, GitHub and BitBucket



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

